env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  indent:
    - error
    - 2
  max-len:
    - error
    - code: 80
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  comma-dangle:
    - error
    - always-multiline
  curly:
    - error
    - all
  dot-location:
    - error
    - property
  dot-notation:
    - error
  eqeqeq:
    - error
    - always
  no-constructor-return:
    - error
  no-implicit-globals:
    - error
  space-infix-ops:
    - error
  no-duplicate-imports:
    - error
  no-var:
    - error
  prefer-const:
    - error
  prefer-template:
    - error
  sort-imports:
    - error
    -
      ignoreDeclarationSort: true
  array-bracket-spacing:
    - error
    - always
  arrow-spacing:
    - error
    -
      before: true
      after: true
  comma-spacing:
    - error
    -
      before: false
      after: true
  no-multiple-empty-lines:
    - error
  no-trailing-spaces:
    - error
  no-tabs:
    - error
